name: Write JS Array File
description: Write a JavaScript file declaring an array (supports multidimensional arrays)
author: conbanwa
branding:
  icon: file-plus
  color: blue

inputs:
  js-name:
    description: JavaScript file name (e.g. data.js)
    required: true

  array-name:
    description: Array variable name (defaults to js-name without extension)
    required: false

  values:
    description: Array values (JSON or JS literal depending on parse-mode)
    required: true

  value-type:
    description: stringified | number | boolean | string
    required: false
    default: stringified

  field:
    description: If field is provided, array-name is treated as an object.
    required: false

  parse-mode:
    description: json | js
    required: false
    default: json

  decl-kind:
    description: Variable declaration keyword (let, const, var)
    required: false
    default: let

  export-style:
    description: none | named | default | commonjs
    required: false
    default: none

  pretty:
    description: Pretty-print output
    required: false
    default: "false"

  overwrite:
    description: Overwrite file if it already exists
    required: false
    default: "true"

  dry-run:
    description: Print output but do not write file
    required: false
    default: "false"

outputs:
  file:
    description: Wrote JavaScript file name

runs:
  using: node20
  main: index.js
